apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:dTI2SyHGSZhTrgHi2NNeQUJARbrbYZo=,iv:5hQaADPnfmsamAxe4Lmftf/CfgbJ7n3JMI0bYK5nIZc=,tag:AoQz1oZCUKtnpniP0E8RGA==,type:str]
  password: ENC[AES256_GCM,data:HxPk8zqzV5KkFfCwfaseiNFFIGYocWuSigs4DHwteVRT2MT7ESG8gQmzL/WCQWYnb/J8A1waAa6gNWE73nfUfQ==,iv:KRqNQ65USVJntb8ONeIoPKeoLUEY1Lmyd8/+mFlrlk8=,tag:e129coRpkfAc8knGBIzWCw==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T18:54:53Z"
  mac: ENC[AES256_GCM,data:mJg3OJqIYBObM27Mn6YB+BmTkOL/cFJ8okT5tOUsgF0+APK1WamiCb0W9sy9Fm6aI84ak+ZXGmwHCGaddJD5V08NvYbpC3awpUML0EEl5YtzmQQAenPpW87tBTFCdyQvNWpL1EFtXnZlTPcdPrf94YyUs9Qi7wS158KSphZ7oBQ=,iv:ljeWhJuXS0+5+2iy2GZXUTzJBKnbBINAjXTN2/UU9sQ=,tag:GpHu/9j94jtg3Rx7ey5hpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
