apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-ro
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Q5QbbM799LA7hbaTo98GA9nQBZMX,iv:uVHmcbE3FwzTQqyCQCCj/u4WfxFXJoU0/AHkZz4u9Kk=,tag:iVMVkRLTi0B30OCDzANy9g==,type:str]
  password: ENC[AES256_GCM,data:HS7q6esIaOtX5O3uS+omdO7cXffP8b3ezx7+YSfzHMiyrUlbZxxg9LDVMQbSXsKeFqzG/YKF7jOxz95LDv16pA==,iv:x5FqOV0AVur7Z0ywvqTGQ4OOi5F8X4NFxMGito356E8=,tag:wtI6QGJsgKKa9PMVjXp68Q==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:52:52Z"
  mac: ENC[AES256_GCM,data:0NFUEayGDVqknuUvAJJD6g1mW701LkEVhyOTgySIJK/LE9+xJ1xXEt3h9THF07CkrXZ+nnTSgMjpqbXUSV8Ol+lExee98AnS3iLPrBv9ergg9jRf5YsXKFXM1WSNY5Dj6suUdT6DAqk8Hgc4PEHiejzadyWRj5SxeIqwQu4jzjE=,iv:5dhNQO3bNonczQ+flXYnZnjvBR76y6Kayh36Rz0yH+U=,tag:MsPWfyJLxieqbhp73F3NVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
