apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-owner
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:wev8fwdMWsLHgOQ0Cm3YgMRgIxZon5vV,iv:mdIVTezxFNJ+pAxYFktZLtIgsO1XLfj5bq9ayIeRfwU=,tag:M7aAMCTANi4i53Cu+7mccw==,type:str]
  password: ENC[AES256_GCM,data:HxPk8zqzV5KkFfCwfaseiNFFIGYocWuSigs4DHwteVRT2MT7ESG8gQmzL/WCQWYnb/J8A1waAa6gNWE73nfUfQ==,iv:KRqNQ65USVJntb8ONeIoPKeoLUEY1Lmyd8/+mFlrlk8=,tag:e129coRpkfAc8knGBIzWCw==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:51:31Z"
  mac: ENC[AES256_GCM,data:GS6mBuWuHtu0r0X1WFBiWGVRCY+lgxpyggDr3FtfarYYq1sFUIQ70z6BU92PrsJWmCXqvFlER3BkUnloYY1k/AsmUXY4/rEc6NpwbF8Vi0vRQgyqYy51YPpI6Yi9ZcXl7Kad6L2d9/Gam4/+cnRAS0bOsQCEInFxyt7a1XHAnT0=,iv:Q0ioEV+C5+Rhpj2LOPePur0RQ9/OknomxUz2keVogsw=,tag:4VJDFC2CZYY9Mc5vaWYzfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
