apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:S3MAkWWog1cZcqr30F28EN7+,iv:OpbDmbseuK3xjD5c0XpXo2FLo6o0cR+TDZXROrS/k6o=,tag:hhIib5kMBDxgtdxAYVeWsw==,type:str]
  password: ENC[AES256_GCM,data:HxPk8zqzV5KkFfCwfaseiNFFIGYocWuSigs4DHwteVRT2MT7ESG8gQmzL/WCQWYnb/J8A1waAa6gNWE73nfUfQ==,iv:KRqNQ65USVJntb8ONeIoPKeoLUEY1Lmyd8/+mFlrlk8=,tag:e129coRpkfAc8knGBIzWCw==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T17:22:19Z"
  mac: ENC[AES256_GCM,data:JDz3yNaJxTsVC2dK87uOmZ3iyjL19aydc/j/pTa2pVuMMksTiQssxKppwxjcDX7AW+MieyDtT+oQnSfeATkpaBmnoWyVYQspfYLsv18LFVGzf/BBaWxFSgZj2Y6PS+vhE2DP0N1fq2XqJHhi36YJRw5svQ94BMIzui5gKh5ju6Y=,iv:3/vFWLsLJQWTL78vZqLLSVqa5E7nwuiENCnihYAYQi8=,tag:RG1hlxbHMiixt5vFCP8htg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
