apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:gVucbMdQEPrB9EaniLJ3sjeSXImGcwKziA==,iv:hcuzAenL0sejTe7RuyXdcN+aL7mGyR+eO700xxTOFgM=,tag:/4rgdxOUq6TeGt2KuwJPUg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:4YYXbve270HMdih2p5fGr1p2tw4XDq0beIIATypwlw==,iv:BA/TKDFkZyZ5pZfi6VZ+VuuEToyi1e2E1HHVpapUJ54=,tag:kYU/mcLOaVPPg5N8VQMYeA==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM29kVzYrRUJqN1pJdEpM
        bmZhYjkvSm9OSlJmRDlNQURpb0t5eWdXR0gwCnMwekVWb1huK1RNYzZTNHJKRGFy
        V2lLcGdBNWpiaGV2bXcvMStFeUNldmsKLS0tIFNnT0tlbUpVRzNsSVA2OHlQZmt2
        dlRLYTgzT1ZLWDJhZWpieVZoM0MyeEEKIStoz3hqsVrBgrakYI44gGgpPP02ORwx
        kvBKihb1Xt6RhP1F46sMqer4HHG6KLcUiBuRBYCozlLzBeP2TWmL3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:43:33Z"
  mac: ENC[AES256_GCM,data:9Ak+Opei73jOgu/+CJrTjAPWJycyjMkbsu6xqXKxnE9eMXl/BgNBTD6/E87xoYjploOLsZiML6atCeSqHqJ91SRJVYr+E/bshPEOdMlaPi2QPmyAPAYCk0svfdD9jop7VEWuSxddpxBRFbTHJD/dgBKLeeGivNxCdG5q2tanfX4=,iv:xhuMPsyglu7o4h7R9NKAx9gPDcbXrAgInWZ4K+mtyCU=,tag:7KUR/TJCMsvak+dYgqlXmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
