apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: test-db
spec:
  name: test-db
  owner: test_user
  cluster:
    name: cluster-example
  extensions:
  - name: bloom
    ensure: present