apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-test_user
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:lf3OQ+3tLt+X,iv:DfTd8Wwj5Ea5w6ZX9fPTKVIyHEEWr6R7Ww92tSlPzBk=,tag:9S1UfLAq3lkXMGvttYIhrQ==,type:str]
  password: ENC[AES256_GCM,data:SsKk0H3ftzjzcwSv4q+SQVoBQT4ucVBSQoWaNjVoKnIUH7ndmIGgH29MWwXteMZSt0Pd3mMU3qSUQNgIM6XZLQ==,iv:/oxhgz+naUN10FlUu9fPdRZxD0wu0PlmSg/jAXOiozw=,tag:2PCS6rCY2wyj4R9PNjo1Ug==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:24:32Z"
  mac: ENC[AES256_GCM,data:hJe4ARw1tR9SSvytuee3UuzugbyOeQ0oyuw6SSSDt+mhWHjFeG+XAK5QZpeGeWlx3wCLzZCfcPKm+Jz255R+5nWtTkZpNxm+oZ551Q5rdLMH/a03eTQc/p0ZznGtGqsDrwc9p98YY+UA2LL7TdggF0EPaMAJf0KyKy00ptTIF6U=,iv:3aergEBP6+6KrH8Y/Gpgvvx7dQxq8OtEf3ItYmEz76E=,tag:/hihwL3FjG81Yx1uGOxwHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
