apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-test_user
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:ngJjOsXKM984,iv:k3ZCaafdaMEt8NjAy8c2xCD8+qXSy204lVJUi2EUxGo=,tag:iOF5tj+xehXCvvpQNz5aIQ==,type:str]
  password: ENC[AES256_GCM,data:T/Xm2YMs0zU8jB6Yv4P301ecpqVCRVcJuF/yT4xZOBpoUomAx3KaQBTCeZCxWYe/K62F/hdRwltbbZkVwC1PrQ==,iv:TDvjnIWEk6rD/tHL6ryCqgZnwl4J2y5/OPxMr/59YmE=,tag:KKKuBrBOWXDsI+0AI4PJaQ==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:32:50Z"
  mac: ENC[AES256_GCM,data:epNGIrjWTqgboIDiCVJg4bBcB1FoM8JhBAhptB7RUrQE5Wxef5nTzhCreBDPwkgU5B2XJ7/WFJGSi37oaFijpbWhawqBe1WJo43K9BTuV22BYhNuYjRkpnIDPn79LEcDKAUY9FWNnBsLDPLXpfe3x9KeecNaCX92D53lXULaF70=,iv:ZRDcsPFp4ftmd+k5RHcyebFU5ithbEslGpgMaDoIs+Y=,tag:D3zxhA+vHS4qYxgP5C4KbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
