apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backblaze-s3-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 003fd3f04b79e350000000003
  AWS_ENDPOINTS: https://s3.eu-central-003.backblazeb2.com
  AWS_SECRET_ACCESS_KEY: K003Yk8JzvbAH+wvyoGNQgFCMM9Fs88
