apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: default-enforce-memory-limits
  namespace: default
  annotations:
    policies.kyverno.io/title: Enforce Memory Limits in ValidatingPolicy
    policies.kyverno.io/category: Other in Vpol
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30"
    policies.kyverno.io/description: This policy ensures that all containers in a Pod define memory limits.
spec:
  evaluation:
    background:
      enabled: true
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  validations:
    - expression: "object.spec.containers.all(container, container.?resources.?limits.?memory.hasValue())"
      message: "All containers must define memory limits."