apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pg-policy-reporter
  namespace: database
spec:
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchLabels:
      cnpg.io/cluster: pg-policy-reporter
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      relabelings:
        - sourceLabels: ["cluster"]
          targetLabel: cnpg_cluster
          action: replace
        - regex: cluster
          action: labeldrop