---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backup/backup.yaml
  - ./backup/objectstore.yaml
  - ./monitoring/podmonitor.yaml
  - ./secrets/pg-authentik.secret.sops.yaml
  - ./secrets/secret.sops.yaml
  - ./pg-authentik.yaml