apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QOKHyfDRD7cYsuUALF0uXAI05VD/Bf91Ew==,iv:DHYuUe1vcPNzsoAI7dKwXRbS7SJ8h6vmuO9o5rmLv54=,tag:725UHegtLdKPrr5zYjN6rg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:rTk1V6niwuAtHFs8UMRMfzBIguQdGkAwZfUp/TFleyONAnR+0bqOw7Q=,iv:odCN0I80fNPidxfcObhlEuYJQAwtpV2U4QRHS7sIFzE=,tag:vzFpmEOSnriI+Q9NJSvwng==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7OmKb1tfExzdLypMSz04yRZMJoSDe2PFS39P3/HyrA==,iv:jTV5ymHOur8QT3AHj82FAftmRJF4OHZUL72fq+JyPEY=,tag:zEhFYIDO6KGNWwL41u4ZsQ==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS0thWU1QVHdQb0l5R2Y4
        S0JTMmNhT1NWSjZLVTZXMHhkUHpDazBCN2pRCmJSdytBbExjYzBWK1dxcXZLQkhD
        VUdOM3p1N25jcThMaDd2S2hIc3pPSXMKLS0tIHNLUnVhck5aVmd6TUJua2pSWTFT
        YVV6SUx0SjZXVDdKaTZ4K1F4bkV1TGcKJFNq68U/s5JvVKWS2KnLfSd5CgMd8G35
        ual9wDnd+v3oxNYovNM+ii00QV0sqsM5zoLA2VxkPu89P+ZeLGBE7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T14:41:23Z"
  mac: ENC[AES256_GCM,data:el7m3H4Kvo1hOFgyU5uEM7pI4pvpJmckHZ0PX8OIk+FL9YQFib5XyXYPcWp42W1KsQs9W9OAzQcKc+L49Lc46ZcJttWINAqSDaO2UWcnhWaNhDWXQzz33sfGpox2Hn+icidBEnmH2rD4GirBE9tgswTKYmv38h0FsfSG/ak8oJY=,iv:a/oP42VfDzAwgWNOIZ4AEfyfdCk4GhWq5ZDiYOZxTyk=,tag:20e1hBGuRXcpDJJBIzOrVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
