apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-test-user
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:osC5jGsysESf,iv:X0DOR+/jCaPV0wrUntPkhhDYO20wdQYfw3j3jSJA7nc=,tag:wW0upFpZ2N5R1fiO6WgN0g==,type:str]
  password: ENC[AES256_GCM,data:T/Xm2YMs0zU8jB6Yv4P301ecpqVCRVcJuF/yT4xZOBpoUomAx3KaQBTCeZCxWYe/K62F/hdRwltbbZkVwC1PrQ==,iv:TDvjnIWEk6rD/tHL6ryCqgZnwl4J2y5/OPxMr/59YmE=,tag:KKKuBrBOWXDsI+0AI4PJaQ==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T18:34:39Z"
  mac: ENC[AES256_GCM,data:sGd85IDDlN2gyegd6OR7/d74hduEMweAI7k+g7v2zPTzFquPEhY3WZb7fau6SAAViqWVcYZR5JRcBBQVo9CpFpzgDVINcU3DVxzyMpV756DGI/x7EJfZBDC1imfKO46Vyk8cxyrf9AElQC3bqL8a+cBTtA4JiSWOgicosP8iZiU=,iv:Wom87sCMdbLLAbv71C4tN5XnGKDpZ1ZbmaYMGN2pPlA=,tag:NdO4vr1vRxPm58M1x+38SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
