apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:Exi+PJP1IJWcz55YbGUgF8J3H3eH8vZttw==,iv:ex4wh6NaMSZuf5omy4jQREV2XLJl6bvdQxM7+Xe4AZ0=,tag:8hkwAsBP6QKkO3ZB+X8hhQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:XOZWJyfVzjIXDoabPHyumnMHKyIBc74ljCz+HVON/g==,iv:ntvIEuRVLyvXDpPLMkWINKTcLoQrsTMU0sTfLrL4gik=,tag:JFQV60ytLAlSYDeBZvN0kg==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM29kVzYrRUJqN1pJdEpM
        bmZhYjkvSm9OSlJmRDlNQURpb0t5eWdXR0gwCnMwekVWb1huK1RNYzZTNHJKRGFy
        V2lLcGdBNWpiaGV2bXcvMStFeUNldmsKLS0tIFNnT0tlbUpVRzNsSVA2OHlQZmt2
        dlRLYTgzT1ZLWDJhZWpieVZoM0MyeEEKIStoz3hqsVrBgrakYI44gGgpPP02ORwx
        kvBKihb1Xt6RhP1F46sMqer4HHG6KLcUiBuRBYCozlLzBeP2TWmL3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T14:51:25Z"
  mac: ENC[AES256_GCM,data:LzHyGCMhkqUzP+sF0wpVQdJeAU4kbWAmFxZ3nXaiyTHR9HZuhspxL/yE7yF/kLhOBRTVIdNXH2wn+otqWltKiuId1CCEKojtrbemFFhf6EJSEv0BfDijtZLPyYR+PWz/87sTmy3xFSBgytJxrfWa46Atu24ucT/W3IopDiMTg1M=,iv:WEREwUdvV1dIU3KCgfUJrF8OQhiH1oq9wLErfs0TIJY=,tag:jltZhHlrnXuvllpQ+zI0ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
