apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:D3sP9sfVN+pqOwg6JKfXb/qqYcsZ6+iyyw==,iv:/Lx9kExMUxZ1GIVVEJB5cJ6JZU3+crbTvKw2DrfrdmA=,tag:nulXHrKuhNxB8mItVevGVQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:D5dZ+Z4O8LBGPfTd+/3qyaW74+leThNhUHyHj5iSBA==,iv:1UqXo2Nlf7gFaoToBfiYh6H/FKi57I5yCDhoeHrazes=,tag:Q0X9uS6JZxs8OZ5Mub7H6g==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM29kVzYrRUJqN1pJdEpM
        bmZhYjkvSm9OSlJmRDlNQURpb0t5eWdXR0gwCnMwekVWb1huK1RNYzZTNHJKRGFy
        V2lLcGdBNWpiaGV2bXcvMStFeUNldmsKLS0tIFNnT0tlbUpVRzNsSVA2OHlQZmt2
        dlRLYTgzT1ZLWDJhZWpieVZoM0MyeEEKIStoz3hqsVrBgrakYI44gGgpPP02ORwx
        kvBKihb1Xt6RhP1F46sMqer4HHG6KLcUiBuRBYCozlLzBeP2TWmL3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:50:38Z"
  mac: ENC[AES256_GCM,data:/5wT0uJxTYDLTDYWnc6f6uVRmXNCsgbtbVycHJ/Vu0UKc64jndOQAzrkGPNQaylY8gX/sJzvNUvRWEwhKiDPzaqc9HyxhcllD/1PEaTaWkKz5GnX0RqyVHRqvBXyT8nzn1f7Sgd1QRZcN0EJokUnHxp48ugfjMdK4vJZSCKIy64=,iv:+Nzq7W4v6kkraCLwChR65smpYZ+8mm2Fp0aT2aac3Kg=,tag:6zBQmL4yoh70OqD+ZGh6dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
