---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backup/backup.yaml
  - ./backup/objectstore.yaml
  #- ./config/pg-policy-reporter-init.yaml
  - ./database/pg-policy-reporter.yaml
  - ./monitoring/podmonitor.yaml
  - ./secrets/pg-policy-reporter.secret.sops.yaml
  - ./secrets/secret.sops.yaml
  - ./pg-policy-reporter.yaml