apiVersion: v1
kind: Secret
metadata:
  name: papra-auth
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:ZWMyH90eNYNYZ8CYU10SqOToq5UlwTbZh/LkvjkYXyRR8yeHWW/uNDaSzW4J00bo4s2JlVybyTTB18Tbui+YN88FyYFM8SAZtXdER1vaSluUQFwT441n16GEFhk0ecseAPwBcbwSRDqrjfDO238rcLsYb6MFiAEk0PbHd0mGrPc=,iv:G8gptHMdMLJojJaNCbpWrEtKcotN8boi7YtQVfNFyzM=,tag:Ek34QywPh+RuVh/l+3kFqw==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibEF6cktZNFI1enhkZlk2
        WWNHY0JVOVFQakNXdDRoL2NjZFVEd0lqWmxjCkNGRk5WZzErcXdibmFyL0hOSE9p
        NzdtYUdWQVhVQmtGWExTV2ZqR2lLa0kKLS0tIEFBQTBlcFFqbEU5WjJzajdoM1NV
        S05KQTdwKzFTSUpVTjIvYnJTOGtHZDAKMFrtTUES3crtmYbL1/CVHkapxulY96x9
        7y2BBdPDFGpFuhMbMXf0CjdZz6EwXAyXT8UM6Hp6J0sIo3a+Qa0uHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T20:25:46Z"
  mac: ENC[AES256_GCM,data:dHxP30jutZ8J2XBlZkf/DZythsX6LjokiMdEavFY8RvU9xZbve5mdDww7p9KDmwOfjfSe1dX9hiB8Zq07hKF8r/K5SFlPwLQZ5EjYt6EH6Pl4eM/bTMNlggo+Ou4sJvz9OdXYLCoRJxAkQ1V1amvC4Pu19Vpi+cEj86MWptNUI0=,iv:jqpbcAVsn6lGFJBC2W5WEJtbTkwJ0zb315lIa5jVOQ8=,tag:l34k5OgDc7BgrXl+L3cNog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
