apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:wNxKWvj5Ojlb9aWCPCWu7Y+b,iv:4RN+s6foHCX57EWloUhB3aTTvRf3avb1YFQ17e3mPEM=,tag:TYfgM7x7GQCSApjfqkjGPQ==,type:str]
  password: ENC[AES256_GCM,data:PQeRNrxjIsgBlx0EUadnXZnbWrM21Dx9i+otaglXVDSCT9acfmvEKE8HdTz68oxycDfoTedWUMg3493J3F4v4Q==,iv:Axtw0Gtmpl3Kd4tZhJ8cRo+GG9kBCuaGcmy3kh+Gy5M=,tag:tXbUDoHhQBiZzih8IN6V/A==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaEY4Y21vdUM5NGRIaFVn
        bzgxdWhreUVBNldnbDA0RjVoeFNrcEdMYzFzCjkvVTVlL1lLRDlZbHlVd0x6eTdw
        OFkvcEZDVEEzMmRRNW5HR244K2ZOdVEKLS0tIHdpSzZlQXo2SFUxbnBrRVNuTDFM
        eEdNTXV5OWxReEx0Q3hpWG5jajdWYUUKH6ebDNHq6iACPZihtAm9waaGfqlWwIqo
        khdoj0R+JpChStcSeyO47gJ8NLKoUwvl7CKiXeDlRNAmE7yFdzMgOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T19:16:44Z"
  mac: ENC[AES256_GCM,data:KOaQsNbYRCzmb8sKEsf/AWJgy/vYb+pqptyouj8BS3tM7py3dMKprkZv1iKktqwXA9BOL6secJ3uar/5jqzFt5HymZImW9oUrveZcMhOHsRUmIpUpov5oIGep7xBwKvTgy3Iz0S86FN1SFz6yhgiYUI11/gQhof8t8ta3jqaQc8=,iv:m6bjx23l/IkWB01jS6MP5cNYhO+c4QU3ntzLR9HPZco=,tag:T3iewNKxIFGNbN+n4UteVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
