apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
stringData:
  email: ENC[AES256_GCM,data:hhRRtfktZ/oKwgSvMB0=,iv:A0AIPkPO8f1LMT4McWWDM1M2W8lPag9UQI9uNigFuk0=,tag:1irRd8EJcLzCQrZJZZk94Q==,type:str]
  password: ENC[AES256_GCM,data:6MxHrsXmvivgfN6V00dViAAJCVQb249W5eVetUXf9gCeYdossYMFeIrjb3MT/OcwVBxjVwo+T2SPJ6AGw6sXLg==,iv:EgVloibXYFypaVjr/D1zlL8shGpbYeToHvjuSqr4qlU=,tag:GAl+ftZ1B1iRsglck3Z2pQ==,type:str]
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:JjIjZYhxOHc0grzy9J0=,iv:muxc0tN87y0mzHg1CclLoEtlm4XdEaKBpeOv84W3SJI=,tag:a8AypI4L0byLVqy5mZ5ruw==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:KWXV71XAMVDx4sOKZBxtt1ZSm2SwPPto4VpUT7dbTQxhrmXm/2HzOhbfa4wShklmlEDijMnDystg+S+CXGYfdQ==,iv:dzXMWi7PXJ1Ez/IyOBl/Qpgl8ZkseUrgFhPJjVvHeO8=,tag:/QNPBl/rQV5XGhdSCjUlPA==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ2Q2YmIrbC9NcEt2bnRh
        Tmd0TVZFWnA0aTRMRjBSdFIrMDZOZThQTkY0CjA3Nk5aZnpNa2M1TC9HWjFDS2tu
        M3B6T2tvdnFMWDVzSGU3dGUvenFyUWsKLS0tIHQzZ0JwRkxpa0s0S3lDb1A3NTNL
        VEdyekZET2NadVMzakJsTml0WGpxQUkKXli1mq3zacqwtUBqGiDoaySlu4nB1lu5
        tZdJ1pQSz+DfV4rSts5SN0wFZrUfPQv/9rQ2K8jmrywEp7+k6S1Erg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T20:45:34Z"
  mac: ENC[AES256_GCM,data:4sNCU3uA5lrr+rA+AxnGRsuM3OweKxO6HcOrAr3zkCW6J2vRgovOX+ifGI60eV09+S0zRv3MpXXPsMY8vY3G3AZhpn2IfvPGDWpq9G6l88ZYSN7jOfaElnleQd5Y437njhg7c0mYcUt79/kdW5UO7EVTTzW1grGOxqj20wYQ8sA=,iv:guMD+KfkOsferem1nFQHYgtVTvjQ3oYve9SI6fkM45Y=,tag:8XuvhxczIYkGf8nJw7mCXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
