apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:b6Dy2CTUOiDQeGTd,iv:kngd6LT/gdxrl3XrQkypQBbnYiiqtAHdzWTeQCwV2u0=,tag:sf74Wospz6uCPtcMPBXI5w==,type:str]
  password: ENC[AES256_GCM,data:ulZBT7KsxbxYxdKc2B/v7PEvGkhLhr4GYBr5+FDPY+jpH/e+MVi2u/Ak7c6mS9+Oe2239If7HR8r8ild287WxA==,iv:Qmq/AxunkSRloIa2IQZTZxb3TCmOA73kUFLDdzuE76A=,tag:1u1rDR4m+Jl2kCIAqx7B5A==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T18:40:07Z"
  mac: ENC[AES256_GCM,data:qafr19I06YhuoVUW1ek3kyrMfCXXGYMvIhR9ldgvtxZrpgWJByhHCLkd4qGI9bw0WOBaleakrEZIBIyLUq8Av8Ho+I8H7miC8dRyOirdq17GhPbfXZ846TK6BGEAf1dNkDiz6nIDqJrEHMF5asDFejtds1jwDkZi8ou7BuQ2kPM=,iv:/nSK2VcpVXWMgQzB1x0P4AVFMKNSImGjwS8whRfSzB4=,tag:d0and1uwRfOt1zdmg/hBYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
