apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:kQ3bfb1Ix5O4HEJbZhnYVjAheDPCnnrp1Q==,iv:JzKpdRZqkQgcZfFWf9xI/bo+CauHf4kWDxe1pHBEG4M=,tag:jIPeSCjtv6cYd2AyQnoFdw==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:UkTV52/TVfINhGtHbe1+JI41yfQWlxEulZG/4PUpwg==,iv:5NbZYUWh6BNQXBp+WgVRTTpUzpiYxHyCxavTEvrqHOw=,tag:TLdsELHCgejkjD2UYMY2CQ==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM29kVzYrRUJqN1pJdEpM
        bmZhYjkvSm9OSlJmRDlNQURpb0t5eWdXR0gwCnMwekVWb1huK1RNYzZTNHJKRGFy
        V2lLcGdBNWpiaGV2bXcvMStFeUNldmsKLS0tIFNnT0tlbUpVRzNsSVA2OHlQZmt2
        dlRLYTgzT1ZLWDJhZWpieVZoM0MyeEEKIStoz3hqsVrBgrakYI44gGgpPP02ORwx
        kvBKihb1Xt6RhP1F46sMqer4HHG6KLcUiBuRBYCozlLzBeP2TWmL3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T18:38:52Z"
  mac: ENC[AES256_GCM,data:VgIcJm03iY1I6caZRZ/9vt4hOQYLzWAJjbFSV4T7Szcy8taOVwFuuaubt9kJUgWd/eY5AmbELdlEpCETPZKOyG9S+alXWm22coMAdKptyZMaQRdqfouUH2DugLjT/gZyhozPzuEJm1PIuW+0R9p3jF8vlnHPC1HhfBg6mHw792c=,iv:7PW8R+Rbhja0ME27v4POCfhc+hJUHyRqRgWYZ0JmuyM=,tag:mIOTUJvWJHAKDSh+YiYFxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
