---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./example.yaml
  - ./secret.sops.yaml
  - ./secret-superuser.sops.yaml
  - ./backup.yaml
  - ./podmonitor.yaml
  - ./objectstore.yaml