---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./example.yaml
  - ./secrets/secret.sops.yaml
  - ./secrets/secret-superuser.sops.yaml
  - ./backup/backup.yaml
  - ./monitoring/podmonitor.yaml
  - ./backup/objectstore.yaml
  - ./databases/test-db.yaml