apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backup-cluster-example
spec:
  retentionPolicy: 30d
  configuration:
    #serverName: cluster-example
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
    destinationPath: s3://home-ops-test-pg-cluster-example/
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: cluster-example-s3-secret
        key: aws-access-key-id
      secretAccessKey:
        name: cluster-example-s3-secret
        key: aws-secret-access-key

