apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-superuser-secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:y3GRjzShyZU=,iv:hAEUvKTgAoVCyqgICrtjpbilR+wSDPTXtVwgpTgMhDA=,tag:2bxJk6EdbnCNKZxNnkIzlg==,type:str]
  password: ENC[AES256_GCM,data:dH0GDks8kf5pSojj81IK+zpLCD315axHm900Z7ZnBP/xpHJSl5NGL4sbLQfnMSuVizh4bymc88/gZjuu/LXzqQ==,iv:i4APkVGTkfgMsSXLbWbEXALN8AmBZgTOQmVwxV98+Bg=,tag:ZmCUS1Mc96Hd5JcpDl+kww==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb2lHZUZlcEY3OStrTlhn
        MXY5NGQwS3AvRUVLVS9mYnVWdkVQcUJiUndVCllObWszWGx0YzhpcElLaisvb1U0
        WW5zR3JKODFucWkreFFRQnMxQTc3TWcKLS0tIDVuWDdGalRjSFZML3hIYlBkSmF0
        UmhZN29iVmVIKzNicmpieTd3WWgrMDgK+8G8MD9IEUjY8zSpi3SWkaOpBYHqQotf
        BH2cLcd/dmGZe2z8fy6XtBo3vMTkzIjWUm8uIkiPTtgZjizZCf4PFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:42:29Z"
  mac: ENC[AES256_GCM,data:H4xUVBWiNDpAKo6HEZAnh14JM40GTAqXjsRrgTLvRdIfw9SEkPLJe6vqdNgA1FX6yjoyCUZ0TtU9NdWIlNriVRGtQ6hcsjiTJS8DymishFWKuwwczs+eNPrY/sxYIfME2J8Ti2OuJ4u0GC6Xj4Hok7rP7/Tj2DKN83w9gfJTI1I=,iv:MUILUVJOKwyYTFW2WPuvKt5uLHHw8qtK/KYQCjDHfAk=,tag:SbOZGr5K5NTSYYuBO0EuRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
