piVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:D3sP9sfVN+pqOwg6JKfXb/qqYcsZ6+iyyw==,iv:/Lx9kExMUxZ1GIVVEJB5cJ6JZU3+crbTvKw2DrfrdmA=,tag:nulXHrKuhNxB8mItVevGVQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:D5dZ+Z4O8LBGPfTd+/3qyaW74+leThNhUHyHj5iSBA==,iv:1UqXo2Nlf7gFaoToBfiYh6H/FKi57I5yCDhoeHrazes=,tag:Q0X9uS6JZxs8OZ5Mub7H6g==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM29kVzYrRUJqN1pJdEpM
        bmZhYjkvSm9OSlJmRDlNQURpb0t5eWdXR0gwCnMwekVWb1huK1RNYzZTNHJKRGFy
        V2lLcGdBNWpiaGV2bXcvMStFeUNldmsKLS0tIFNnT0tlbUpVRzNsSVA2OHlQZmt2
        dlRLYTgzT1ZLWDJhZWpieVZoM0MyeEEKIStoz3hqsVrBgrakYI44gGgpPP02ORwx
        kvBKihb1Xt6RhP1F46sMqer4HHG6KLcUiBuRBYCozlLzBeP2TWmL3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:17:36Z"
  mac: ENC[AES256_GCM,data:PIS4I0DEUTPdXH8lZH6EXUhfTLSqvfh0RKInwwpbwwIbrt5rUeT4Nr6m2Ivhei60LOmbP+rJBGPF8CRYEsaTXA2ejO2tysHFYLdzAOZ6Y9m5+UTekOSraaFa5L8hKuHR44N4sws7NUm37l+ypd7l91/JlMLpX7i2flSebQgTb2g=,iv:DzKCBZpPJ2aL6WacN/vsEMx8ylFETuYTX+IyNsvUpIU=,tag:D0xzbfzTngr54cz9j7Y3XA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
