apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:b6Dy2CTUOiDQeGTd,iv:kngd6LT/gdxrl3XrQkypQBbnYiiqtAHdzWTeQCwV2u0=,tag:sf74Wospz6uCPtcMPBXI5w==,type:str]
  password: ENC[AES256_GCM,data:ulZBT7KsxbxYxdKc2B/v7PEvGkhLhr4GYBr5+FDPY+jpH/e+MVi2u/Ak7c6mS9+Oe2239If7HR8r8ild287WxA==,iv:Qmq/AxunkSRloIa2IQZTZxb3TCmOA73kUFLDdzuE76A=,tag:1u1rDR4m+Jl2kCIAqx7B5A==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnJvUDZraWxuc2lQZ3I1
        NVZyZEtrNzN0SDMxQUtlblhPcUVOS0ZnOW40CnRUeHhkYlZXc0xqVEluN1VsSjNY
        YXovdFpmQnNJdXZ5RHhHL0VHbWpuTmcKLS0tIDZ6ak9rQlV1dmgrV25ORmxYNDlu
        QVV4N2VHdTF6RjduY1Rsbmc3eHM2TVkKxpRiurXawJbJjxVlY/7noa+9ygx328/J
        B2jdRk0JYar4ivLoYEtxQGxKi+XF6QvLSBdLsxTtKe/WaUbjZLXmjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T19:07:44Z"
  mac: ENC[AES256_GCM,data:5Q5TeolXKKsZHhf59zl1+MH/gcY4eAKOaUO7i/JwkBEHFnynf0WKmc4eUT7P4WQL7NyikBCnV5jt1oYY2a2esi8CnDkhP6WO2wTwaP88I7c29mvLZEtHpCHd3oQopwcUx1XWmzuXpvgd6QTt6J1tMmAvY34ZWv+5So/CqJ5Jz3w=,iv:NjKuPBBlR2PXba8E4i8+meV4MpSSfaGXLkqTRteJA0M=,tag:t/ONto8HGMnj+Q4cwMxj+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
