apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: auth
type: Opaque
stringData:
  secret_key: ENC[AES256_GCM,data:ZcZ6WfXL0Fmpgi9kq85w34rcRL1mTVAgno9BaJ4h0OGwsRpxVyB4U95NlG1JFM2KQtYYfO21CvKsUzIIvjNFhQ==,iv:5QdUBdl3Vpw7kiRuSdwxbq+NkwGhNAlfu09wTy42Fj0=,tag:4L+6gtUlsW1/scvViuK9pA==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc2Y0Y1JFbUs1U2Zqc2Nl
        Zmdpa2JGYjc5ZkJDSzhwamxvUTlmS3pmWUNBCm1UUTF5ZU1CMzNVV1VMNlN1dkpM
        dkEwNXE5QUxldEcxQ0tLVlZKaG1OK1UKLS0tIGsyaUJ6Ti9oNVdvTUtqQ3pCQ2di
        WGUwMjArR2lFZ0YxYUp5eGloVFNISG8KHh3s9u2Dmnn5feb4bmeR0e43RFcEG+sw
        gTBwifcsch5hJKt8lcctwo5Jt84nc5Z0a3wppLhUOvMUYpx9HwCxvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T20:28:26Z"
  mac: ENC[AES256_GCM,data:jTHbOsQ1kZYI/nWNyrCkLvFMvD7AaXftYWFf70IYMOyFp4m22FpIaCAn2azp/OsuuvQTJnUz5Ca30I9zATBVgeCOkUlHElni7T+zdqTMhroe15AEqBrduQehDg6vDyZ7e2s3EfasZFJvhd1bUip+7n1eu4XeAaQJTU0HW30H9pg=,iv:xnHfaoqx5eUec8r2DDjLfmKpXl/BoBlESsTxbAce7I0=,tag:J2Pn1MhUVQcAwpdYxgEQXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
