apiVersion: v1
kind: Secret
metadata:
  name: talos-etcd-s3-keys
  namespace: kube-system
type: Opaque
stringData:
  accessKeyId: ENC[AES256_GCM,data:6Sg6Nkpy+lo7UZerecJVO41hMDWB/qFNtQ==,iv:FihhP+sK1et02LsFeOQtyKmb4/bplTPzWzlPPZ3nmbw=,tag:o3acldZgSRmvXkb5s3fPNA==,type:str]
  secretAccessKey: ENC[AES256_GCM,data:b+lAmUCW3wJNAkUU+ORuFl5MFcsX7nRScqso0Nkf5A==,iv:kj4mxLLBUQSh9mBYWVlaZpO5bY94J2L1pGK61SdVKds=,tag:sjQsImbHcuHDtn6FS9BRiw==,type:str]
  resticKey: ENC[AES256_GCM,data:6vrLiAlYyUj5NBalauVgb83teP9Hlj28chPB38KVDM9EZRl9RmDcnAUIioM=,iv:MvvfC2SyBgd2xVDisyrve06rlyFwOZrU+ptkZuhMZ8o=,tag:iADhdkt8DZdUSlG9RvowrA==,type:str]
  bucketName: ENC[AES256_GCM,data:L8GcCcNmkX7wdkkhpCwRmsNOrzxQiln/L9N6+SQjxOIQCEEJCwhgluwBtdsu/wMojfbl7bvCd7Q3Yc5uvFg=,iv:AFE2leyZFKAos3G6PMoCvrZTJfrq3T+H7OO2Omu2ppU=,tag:tSLOXiT76MkDFpSsiMdZCA==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTTlZbXpNODB2aEU2T2J3
        Wm1uNmc1NGNRcWorMDJ5aklxWDdjcmplTURNCklab1BIREZNUVFlV0dic0kvVVZE
        dFJVamUxbE9ISVJjQXNaZnRMWjhFSXMKLS0tIFhoNnN1OHdDbVVtc2NPR3Y5Y3hU
        ZUdoSXM1RWQ3Y0VySml5Y2Q5NEN1cmcKSQf8AK6YACY5I6qkccRHhfIAiYFd08Nu
        JmJ8JLxdeuViRzT/JtQeshT6DVlsyP458symvD3mJhLNFzvecAjVBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T14:48:01Z"
  mac: ENC[AES256_GCM,data:rF/Bx8HYkc+9lbZcC7GyfyVtB8NQ8fgWh6x6q/Y15Q3A0JebSHqsyrogHF9Reid7O4+BEzVpxi6VYoU/T7fHFxZ0+hQLWgbJVgVMIdV8xOzWvu21CWUoIGC6fJfA2fGkRVO3TVQFuMpLthZyWa706e0i9H9NsseLKooX8/aRTJY=,iv:69CIjwCmtoytBZVO96YktXcEOlcUcIzSigyduGznsts=,tag:FOek9aC4K9wHS/AIkxKWDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
