# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./default-drop-all-capabilities.yaml
- ./default-forbid-cpu-limits.yaml
- ./default-enforce-resource-limits.yaml